spring:
  application:
    name: kings-twit
  profiles:
    active: local
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /api-docs
server:
  port: 8080
  servlet:
    context-path: /api
